# Data args
is_query_positive_alignment: true
is_reconstruct: true
langs:
- en
mask_probability: 0.5
max_seq_length: 512
neg_per_sample: 1
num_workers: 8
number_training_samples: 1_000_000
pos_per_sample: 1
use_retrieval_data_only: false

# Model args
attn_implementation: flash_attention_2
connection_type: ff
dropout: 0.1
encoder_backbone_type: llama
encoder_lora_name: null
encoder_name_or_path: meta-llama/Llama-3.1-8B
is_freeze_universal_learner: false
loar_r: 16
lora_alpha: 32
num_added_tokens: 1
universal_learner_backbone_type: xlm-r
universal_learner_lora_name: universal_learner
universal_learner_name_or_path: FacebookAI/xlm-roberta-large

# Training args
activation_checkpointing: true
checkpoint_dir: output/llama_alignment
checkpoint_file: null
checkpoint_interval: 1000
devices: 4
eval_batch_size: 64
gc_chunk_size: 16
global_batch_size: 256
grad_norm_clip: 1.0
is_alignment: true
is_distance: true
learning_rate: 0.0002
log_interval: 1
logger_name: lusifer-llama
logger_type: wandb
loss_type: NTXentLoss
max_epochs: 3
max_steps: 25000
min_learning_rate: 1.0e-07
model_revision: llama_alignment
nodes: 1
only_load_model: false
precision: bf16-mixed
quantization: false
seed: 777
sharding_strategy: shard_grad_op
strategy: fsdp
temperature: 0.05
use_cpu_offload: false
use_miner: true
warmpup_proportion: 0.1
weight_decay: 0.0
