# Data args
is_query_positive_alignment: false
is_reconstruct: false
langs:
- en
max_seq_length: 512
neg_per_sample: 16
num_workers: 8
number_training_samples: 10000
pos_per_sample: 1
use_retrieval_data_only: false

# Model args
attn_implementation: flash_attention_2
connection_type: ff
dropout: 0.1
encoder_backbone_type: mistral
encoder_lora_name: encoder_lora
encoder_name_or_path: mistralai/Mistral-7B-Instruct-v0.3
is_freeze_universal_learner: false
loar_r: 16
lora_alpha: 32
num_added_tokens: 0
universal_learner_backbone_type: xlm-r
universal_learner_lora_name: universal_learner_lora
universal_learner_name_or_path: Hieuman/xlm-aligned-for-mistral-v0.3

# Training args
activation_checkpointing: true
checkpoint_dir: output/xlm-mistral-cl-phase2.test1
checkpoint_file: output/xlm-mistral-cl-phase1/lastest.ckpt
checkpoint_interval: 500
devices: 4
eval_batch_size: 128
gc_chunk_size: 1
global_batch_size: 16
grad_norm_clip: null
is_alignment: false
is_distance: true
learning_rate: 5.0e-06
log_interval: 1
logger_name: xlm-mistral
logger_type: wandb
loss_type: NTXentLoss
max_epochs: 1
max_steps: 100000
min_learning_rate: 1.0e-07
model_revision: xlm-mistral-cl
nodes: 1
only_load_model: true
precision: bf16-mixed
quantization: false
seed: 888
sharding_strategy: full_shard
strategy: fsdp
temperature: 0.05
use_cpu_offload: false
use_miner: true
warmpup_proportion: 0.1
weight_decay: 0.0
